#!/bin/bash

#************************************************
# Global Variables

export BASH_PID=""
export SAMPLE_TIME

# Serial Initialization Settings
export SERIAL_PORT=""
export SERIAL_IS_OPEN=0
export SERIAL_DATA_RECEIVED=""
export SERIAL_DATA_TO_SEND=""
export SERIAL_PID=0

# Telemetry Settings
export TELE_PID=0
export TELE_DATA_RECEIVED=""

# Ultrasonic Rangefinder Value and Pin Variables
export ULTRASONIC_SENSOR_1=0
export ULTRASONIC_SENSOR_2=0
export ULTRASONIC_SENSOR_3=0
export ULTRASONIC_SENSOR_4=0
# export ULTRASONIC_SENSOR_5=0
# export ULTRASONIC_SENSOR_6=0

# Final Motor Output Settings
export PWM_LEFT_POS=0
export PWM_RIGHT_POS=0
export PWM_LEFT_NEG=0
export PWM_RIGHT_NEG=0
export MOTOR_RPM=0

# PID variables
export PID_INTEGRAL_1=0
export PID_PAST_STATE_1=0
export PID_INTEGRAL_2=0
export PID_PAST_STATE_2=0
export PID_INTEGRAL_3=0
export PID_PAST_STATE_3=0
export PID_INTEGRAL_4=0
export PID_PAST_STATE_4=0

# IMU variables
export ACCELERATION_X
export ACCELERATION_y
export ACCELERATION_Z
export SPEED_X
export SPEED_y
export SPEED_Z
export DISTANCE_X
export DISTANCE_y
export DISTANCE_Z



#************************************************
