#!/usr/bin/python

import os

acc_x = float(os.environ['ACCELERATION_X'])
acc_y = float(os.environ['ACCELERATION_Y'])
acc_z = float(os.environ['ACCELERATION_Z'])
speed_x = float(os.environ['SPEED_X'])
speed_y = float(os.environ['SPEED_Y'])
speed_z = float(os.environ['SPEED_Z'])
dis_x = float(os.environ['DISTANCE_X'])
dis_y = float(os.environ['DISTANCE_Y'])
dis_z = float(os.environ['DISTANCE_Z'])

sample_time = float(os.environ['SAMPLE_TIME'])


speed_x = speed_x + (acc_x*sample_time)
speed_y = speed_y + (acc_y*sample_time)
speed_z = speed_z + (acc_z*sample_time)
dis_x = dis_x + (speed_x*sample_time)
dis_y = dis_y + (speed_y*sample_time)
dis_z = dis_z + (speed_z*sample_time)

print '%(sx)2.3f:%(sy)2.3f:%(sz)2.3f:%(dx)2.3f:%(dy)2.3f:%(dz)2.3f:' % {"sx":speed_x"sy":speed_y"sz":speed_z"dx":dis_x"dy":dis_y"dz":dis_z}
