#!/bin/bash

#*****************************************************************************
# GPIO Functions to be used in the Main script

# GPIO Wrappers. Used as <FunctionName> <Pin>, Pin is the WiringPi pin number.
# Ex.: High 2

if [ $DEBUG == '2' ]; then
	function gpio { # For debugging purposes while coding on the Laptop only!
		echo
	}
fi

function High {
	gpio write $1 1
}

function Low {
	gpio write $1 0
}

#*****************************************************************************
